services:
  frontend:
    build:
      context: ./client
    ports:
      - 3000:3000
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: studentcodehub
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - 3307:3306
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    networks:
      - app-network

networks:
  app-network: