export const GLOBALTYPES = {
    AUTH: "AUTH",
    ERROR_ALERT: "ERROR_ALERT",
    SUCCESS_ALERT: "SUCCESS_ALERT",
    LOADING: "LOADING",
    RESET_ALERT: "RESET_ALERT",
    USER_TYPE: "USER_TYPE",
}